version: "3.5"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: builder
    ports:
      - 8080:8080
    volumes:
      - ./:/app

    command: ["air", "-c", "air.toml"]
